import {randomBytes,randomUUID} from 'node:crypto';
import {tokenHash} from './auth.mjs';
import {transaction} from './db.mjs';
export function createFleet(db,{text,fail,now}) {
 const identity=user=>{const driver=db.prepare('SELECT company_id FROM drivers WHERE user_id=?').get(user.id);return driver?{...user,role:'driver',companyId:driver.company_id}:user;};
 const invite=(code)=>{const row=db.prepare('SELECT * FROM driver_invites WHERE hash=? AND expires_at>? AND used=0').get(tokenHash(text(code,'Driver invitation',48,48)),Date.now());if(!row)fail(400,'Driver invitation is invalid or expired.');return row;};
 const register=(userId,invitation)=>{const changed=db.prepare('UPDATE driver_invites SET used=1 WHERE hash=? AND used=0 AND expires_at>?').run(invitation.hash,Date.now());if(!changed.changes)fail(409,'Invitation already used or expired.');db.prepare('INSERT INTO drivers VALUES(?,?)').run(userId,invitation.company_id);};
 const mount=(app,{authenticated,role,wrap,getOrder,saveOrder})=>{
  app.get('/api/company/fleet',authenticated,role('supplier'),wrap((req,res)=>{res.json({drivers:db.prepare('SELECT users.id,users.name,users.phone FROM drivers JOIN users ON users.id=drivers.user_id WHERE company_id=? AND users.disabled=0').all(req.user.id),vehicles:db.prepare('SELECT * FROM vehicles WHERE company_id=? ORDER BY registration').all(req.user.id)});}));
  app.post('/api/company/driver-invites',authenticated,role('supplier'),wrap((req,res)=>{if(!db.prepare('SELECT id FROM suppliers WHERE id=?').get(req.user.id))fail(409,'Submit your company profile first.');const code=randomBytes(24).toString('hex'),expiresAt=Date.now()+86400000;db.prepare('INSERT INTO driver_invites VALUES(?,?,?,0)').run(tokenHash(code),req.user.id,expiresAt);res.status(201).json({code,expiresAt});}));
  app.post('/api/company/vehicles',authenticated,role('supplier'),wrap((req,res)=>{if(!db.prepare('SELECT id FROM suppliers WHERE id=?').get(req.user.id))fail(409,'Submit your company profile first.');const description=text(req.body.description,'Vehicle description',3,120),registration=text(req.body.registration,'Vehicle registration',2,30).toUpperCase(),id=randomUUID();if(db.prepare('SELECT id FROM vehicles WHERE registration=?').get(registration))fail(409,'Vehicle registration already recorded.');db.prepare('INSERT INTO vehicles VALUES(?,?,?,?)').run(id,req.user.id,description,registration);res.status(201).json({id,description,registration});}));
  app.post('/api/orders/:id/assign',authenticated,role('supplier'),wrap((req,res)=>{const result=transaction(db,()=>{const {row,order}=getOrder(req.params.id,req.user);if(row.supplier_id!==req.user.id)fail(403,'Only the company owning this order can assign it.');if(!['Requested','Accepted'].includes(order.status))fail(409,'Reassignment is unavailable after delivery starts.');if(req.body.version!==row.version)fail(409,'Order changed. Refresh before assigning.');const driver=db.prepare('SELECT users.id,users.name,users.phone FROM drivers JOIN users ON users.id=drivers.user_id WHERE users.id=? AND company_id=? AND users.disabled=0').get(req.body.driverId,req.user.id);const vehicle=db.prepare('SELECT * FROM vehicles WHERE id=? AND company_id=?').get(req.body.vehicleId,req.user.id);if(!driver||!vehicle)fail(400,'Choose a driver and vehicle belonging to your company.');const busy=db.prepare('SELECT data FROM orders WHERE supplier_id=? AND id<>?').all(req.user.id,row.id).some(r=>{const o=JSON.parse(r.data);return ['Requested','Accepted','On the way','Arrived'].includes(o.status)&&(o.driverId===driver.id||o.vehicleId===vehicle.id);});if(busy)fail(409,'Driver or vehicle already assigned to an active order.');Object.assign(order,{driverId:driver.id,driverName:driver.name,driverPhone:driver.phone,vehicleId:vehicle.id,vehicleDescription:vehicle.description,vehicleRegistration:vehicle.registration,driverLocation:null});return saveOrder(row,order,req.user,'Driver assigned');});res.json(result);}));
 };
 return {identity,invite,register,mount};
}
