import {useCallback,useEffect,useState} from 'react';
import {Redirect} from 'expo-router';
import {Linking,Pressable,Text,View} from 'react-native';
import {Icon,Tanker} from '../lib/brand';
import {useSession} from '../lib/session';
import {Supplier} from '../lib/types';
import {Button,Card,Choices,Field,Message,Page,s} from '../lib/ui';
export default function Admin(){const {user,api}=useSession();const [suppliers,setSuppliers]=useState<Supplier[]>([]),[notes,setNotes]=useState<Record<string,string>>({}),[error,setError]=useState(''),[busy,setBusy]=useState(false),[filter,setFilter]=useState('all'),[selected,setSelected]=useState<Supplier|null>(null);
 const load=useCallback(()=>api<Supplier[]>('/api/admin/suppliers').then(setSuppliers).catch(e=>setError(e.message)),[api]);useEffect(()=>{if(user?.role==='admin')void load();},[load,user]);
 if(!user)return <Redirect href="/login"/>;if(user.role!=='admin')return <Redirect href="/"/>;
 const review=async(p:Supplier,approved:boolean)=>{setBusy(true);setError('');try{await api(`/api/admin/suppliers/${p.id}`,{approved,note:notes[p.id]||''},'PATCH');await load();setSelected(null);}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const evidence=async(p:Supplier)=>{try{const result=await api<{url:string}>(`/api/documents/${p.documentId}/link`,{});await Linking.openURL(result.url);}catch(e){setError((e as Error).message);}};
 return <Page title="Supplier reviews"><Message text={error} error/><Text style={[s.small,{marginBottom:18}]}>Review identity, vehicle suitability and water-quality evidence. Profile approval expires after 90 days.</Text>{!selected&&<><Choices items={[{value:'all',label:'All'},{value:'verified',label:'Verified'},{value:'pending',label:'Pending'}]} value={filter} onChange={setFilter}/>{suppliers.filter(p=>filter==='all'||(filter==='verified'?p.approved:!p.approved)).map(p=><Pressable key={p.id} accessibilityRole="button" accessibilityLabel={`Review ${p.businessName}`} onPress={()=>setSelected(p)} style={[s.card,{flexDirection:'row',alignItems:'center',gap:12}]}><View style={{backgroundColor:'#e5f5ff',borderRadius:12,padding:7}}><Tanker width={65}/></View><View style={{flex:1}}><Text style={s.subtitle}>{p.businessName}</Text><Text style={p.approved?s.status:s.small}>{p.approved?'✓ Verified profile':'Pending review'}</Text><Text style={s.small}>{p.city}</Text></View><Icon name="arrow" size={18}/></Pressable>)}</>}{selected?[selected].map(p=><Card key={p.id}><Text style={s.subtitle}>{p.businessName}</Text><Text style={s.status}>{p.approved?'Approved':'Pending / suspended'}</Text><Text style={s.body}>Headquarters: {p.headquartersCity||p.city} · {p.serviceArea}</Text><Text style={s.body}>{p.servicesDescription}</Text><Text style={s.small}>Delivery cities: {(p.deliveryCities||[p.city]).join(', ')}</Text><Text style={s.small}>Source: {p.waterSource}</Text><Text style={s.small}>Vehicle: {p.vehicle} · capacity {p.capacity.toLocaleString()}</Text><Text style={s.small}>Contact: {p.contactPhone} · {p.email}</Text>{p.documentId?<Button label={`Review evidence: ${p.businessName}`} secondary onPress={()=>void evidence(p)}/>:<Message text="No verification evidence supplied." error/>}<Field label={`Review note: ${p.businessName}`} value={notes[p.id]||''} onChange={v=>setNotes(old=>({...old,[p.id]:v}))}/><Button label={p.approved?`Suspend ${p.businessName}`:`Approve ${p.businessName}`} disabled={busy||(!p.approved&&!p.documentId)} onPress={()=>void review(p,!p.approved)}/></Card>):!suppliers.length?<Card><Text style={s.body}>No supplier profiles submitted yet.</Text></Card>:null}{selected&&<Button label="Back to supplier list" secondary onPress={()=>setSelected(null)}/>}<Button label="Refresh reviews" secondary onPress={()=>void load()}/></Page>;
}
