import {useState} from 'react';
import {Redirect,router} from 'expo-router';
import {Text} from 'react-native';
import {API_URL,useSession} from '../lib/session';
import {Button,Card,Choices,Field,Message,Page,s} from '../lib/ui';
export default function Login(){const {user,authenticate}=useSession();const [mode,setMode]=useState('login'),[role,setRole]=useState('customer'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[name,setName]=useState(''),[phone,setPhone]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 if(user)return <Redirect href="/"/>;
 const submit=async()=>{setBusy(true);setError('');try{await authenticate(mode as 'login'|'register',{email,password,name,phone,role});router.replace('/');}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <Page title={mode==='login'?'Water delivered. Simply.':'Let’s get you started'} kicker="WATER DELIVERED TO YOUR DOOR"><Text style={[s.body,{marginBottom:20}]}>Choose water, compare supplier prices and follow your delivery in one place.</Text><Choices items={[{value:'login',label:'Sign in'},{value:'register',label:'Register'}]} value={mode} onChange={setMode}/><Message text={error} error/><Card>{mode==='register'&&<><Field label="Full name" value={name} onChange={setName}/><Field label="Phone number" value={phone} onChange={setPhone}/><Choices items={[{value:'customer',label:'Customer'},{value:'supplier',label:'Supplier'}]} value={role} onChange={setRole}/></>}<Field label="Email address" value={email} onChange={setEmail}/><Field label={mode==='register'?'Password (12 characters minimum)':'Password'} value={password} onChange={setPassword} secure/><Button label={busy?'Please wait…':mode==='login'?'Sign in':'Create account'} onPress={()=>void submit()} disabled={busy}/></Card><Text style={s.small}>Supplier accounts require an approved profile before accepting new orders. Administrator accounts are created by the system operator.</Text>{!API_URL&&<Message text="The backend address has not been configured for this build." error/>}</Page>;
}
