import {useState} from 'react';
import {Redirect,router} from 'expo-router';
import {Pressable,Text,View} from 'react-native';
import {Brand,Icon} from '../lib/brand';
import {API_URL,useSession} from '../lib/session';
import {Button,Card,Choices,Field,Message,Page,s} from '../lib/ui';
export default function Login(){const {user,authenticate}=useSession();const [mode,setMode]=useState('login'),[role,setRole]=useState('customer'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[name,setName]=useState(''),[phone,setPhone]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 if(user)return <Redirect href="/"/>;
 const submit=async()=>{setBusy(true);setError('');try{await authenticate(mode as 'login'|'register',{email,password,name,phone,role});router.replace('/');}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <Page title={mode==='login'?'Welcome Back':'Create Account'} header={false}><View style={{backgroundColor:'#083c64',margin:-16,marginBottom:20,padding:28,borderBottomLeftRadius:30,borderBottomRightRadius:30}}><Brand light subtitle={role==='supplier'?'Supplier Portal':role==='admin'?'Admin Portal':'Clean Water. Better Lives.'}/></View><View style={{alignItems:'center',marginBottom:20}}><Text style={[s.subtitle,{fontSize:22,marginBottom:6}]}>{mode==='login'?'Welcome Back':'Create Account'}</Text><Text style={s.small}>{mode==='login'?'Login to your account':'Join AQUADRIVE and get water delivered to your doorstep.'}</Text></View><Choices items={[{value:'customer',label:'Customer'},{value:'supplier',label:'Supplier'},...(mode==='login'?[{value:'admin',label:'Admin'}]:[])]} value={role} onChange={setRole}/><Message text={error} error/><Card>{mode==='register'&&<><Field label="Full Name" value={name} onChange={setName}/><Field label="Phone Number" value={phone} onChange={setPhone}/></>}<View style={{flexDirection:'row',gap:8,alignItems:'center',marginBottom:8}}><Icon name="mail" size={17}/><Text style={s.small}>Use your registered email address</Text></View><Field label="Email" value={email} onChange={setEmail}/><Field label={mode==='register'?'Password (12 characters minimum)':'Password'} value={password} onChange={setPassword} secure/><Button label={busy?'Please wait…':mode==='login'?'Login':'Register'} onPress={()=>void submit()} disabled={busy}/></Card><Pressable accessibilityRole="button" onPress={()=>{setMode(mode==='login'?'register':'login');if(role==='admin')setRole('customer');setError('');}} style={{padding:12,alignItems:'center'}}><Text style={s.small}>{mode==='login'?"Don’t have an account? ":'Already have an account? '}<Text style={{color:'#087ee6',fontWeight:'800'}}>{mode==='login'?'Register':'Login'}</Text></Text></Pressable><Text style={[s.small,{textAlign:'center'}]}>{role==='supplier'?'Supplier verification is required before receiving orders.':role==='admin'?'Administrator access is provisioned by the system operator.':'Your delivery address is shared with your assigned supplier.'}</Text>{!API_URL&&<Message text="The backend address has not been configured for this build." error/>}</Page>;
}
