import {useEffect,useState} from 'react';
import {Redirect} from 'expo-router';
import {Platform,Text} from 'react-native';
import * as DocumentPicker from 'expo-document-picker';
import {File} from 'expo-file-system';
import {useSession} from '../lib/session';
import {Supplier} from '../lib/types';
import {Button,Card,Choices,Field,Message,Page,s} from '../lib/ui';
export default function SupplierProfile(){const {user,api}=useSession();const [profile,setProfile]=useState<Supplier|null>(null),[form,setForm]=useState({businessName:'',city:'',deliveryCities:'',servicesDescription:'',serviceArea:'',waterSource:'',vehicle:'',capacity:'10000',rate:'0.012',delivery:'15',stock:'10000',type:'tanker',documentId:''}),[restock,setRestock]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{api<Supplier|null>('/api/supplier/profile').then(p=>{setProfile(p);if(p)setForm({businessName:p.businessName,city:p.headquartersCity||p.city,deliveryCities:(p.deliveryCities||[p.city]).join(', '),servicesDescription:p.servicesDescription||'',serviceArea:p.serviceArea,waterSource:p.waterSource,vehicle:p.vehicle,capacity:`${p.capacity}`,rate:`${p.rateMicros/1000000}`,delivery:`${p.deliveryCents/100}`,stock:`${p.stock}`,type:p.type,documentId:p.documentId||''});}).catch(e=>setError(e.message));},[api]);
 if(!user)return <Redirect href="/login"/>;if(user.role!=='supplier')return <Redirect href="/"/>;
 const field=(key:keyof typeof form,label:string,numeric=false)=><Field label={label} value={form[key]} numeric={numeric} onChange={v=>setForm(old=>({...old,[key]:v}))}/>;
 const upload=async()=>{setBusy(true);setError('');try{const result=await DocumentPicker.getDocumentAsync({type:['application/pdf','image/png','image/jpeg'],copyToCacheDirectory:true,base64:true,multiple:false});if(result.canceled)return;const asset=result.assets[0];if((asset.size||0)>5*1024*1024)throw Error('Document must be under 5 MB.');let base64:string;if(Platform.OS==='web'){base64=(asset.base64||asset.uri).replace(/^data:[^,]+,/,'');}else base64=await new File(asset.uri).base64();const doc=await api<{id:string}>('/api/documents',{name:asset.name,mime:asset.mimeType,base64});setForm(old=>({...old,documentId:doc.id}));setNotice('Evidence uploaded. Save your profile to submit it for review.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const save=async()=>{setBusy(true);setError('');try{if(form.servicesDescription.trim().length<10)throw Error('Describe your services in at least 10 characters.');if(!form.deliveryCities.trim())throw Error('Enter at least one city you can supply.');const updated=await api<Supplier>('/api/supplier/profile',{...form,headquartersCity:form.city,deliveryCities:form.deliveryCities.split(',').map(city=>city.trim()).filter(Boolean),capacity:Number(form.capacity),rateMicros:Math.round(Number(form.rate)*1000000),deliveryCents:Math.round(Number(form.delivery)*100),stock:Number(form.stock)},'PUT');setProfile(updated);setNotice('Profile submitted. An administrator must review and approve it.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const available=async()=>{if(!profile)return;setBusy(true);try{setProfile(await api<Supplier>('/api/supplier/availability',{available:!profile.available},'PATCH'));}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const addStock=async()=>{setBusy(true);try{const p=await api<Supplier>('/api/supplier/restock',{amount:Number(restock)});setProfile(p);setForm(old=>({...old,stock:`${p.stock}`}));setRestock('');setNotice('Stock updated.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <Page title="Supplier profile"><Message text={error} error/><Message text={notice}/>{profile&&<Card><Text style={s.subtitle}>{profile.approved?'Approval active':'Awaiting approval'}</Text><Text style={s.body}>{profile.available?'Available for orders':'Unavailable for new orders'} · {profile.stock.toLocaleString()} units available</Text>{profile.approvalNote&&<Text style={s.small}>Review: {profile.approvalNote}</Text>}<Button label={profile.available?'Go unavailable':'Go available'} onPress={()=>void available()} disabled={busy}/><Field label="Add stock (units)" value={restock} onChange={setRestock} numeric/><Button label="Add stock" secondary onPress={()=>void addStock()} disabled={busy}/></Card>}<Card><Text style={s.subtitle}>{profile?'Your services and coverage':'Complete your supplier setup'}</Text><Text style={[s.small,{marginBottom:14}]}>Tell customers what you offer, where your headquarters are, and which cities you deliver to. Submit for verification before accepting orders.</Text>{field('businessName','Business name')}{field('servicesDescription','Services offered / what you supply')}{field('city','Headquarters city')}{field('deliveryCities','Cities you can supply (comma-separated)')}<Text style={s.small}>Example: Harare, Chitungwiza, Norton. Include your headquarters city only if you deliver there.</Text>{field('serviceArea','Delivery areas / suburbs')}{field('waterSource','Water source and intended use')}{field('vehicle','Vehicle description and registration')}<Text style={s.label}>Priced water service</Text><Choices items={[{value:'tanker',label:'Bulk tanker'},{value:'bottled',label:'20 L bottles'}]} value={form.type} onChange={v=>setForm(old=>({...old,type:v}))}/>{field('capacity',form.type==='tanker'?'Vehicle capacity (litres)':'Vehicle capacity (bottles)',true)}{field('stock','Available stock (litres or bottles)',true)}{field('rate','Price per litre or per 20 L bottle',true)}{field('delivery','Delivery fee',true)}<Text style={s.small}>Prices use the server currency. Editing this profile resets approval. Stock represents units available after existing reservations.</Text><Button label={form.documentId?'Replace verification evidence':'Upload verification evidence'} secondary onPress={()=>void upload()} disabled={busy}/><Text style={[s.small,{marginTop:10}]}>PDF, PNG or JPEG under 5 MB. Upload business and water-quality evidence for review. Approval does not replace independent quality checks.</Text><Button label={busy?'Please wait…':'Submit supplier profile'} onPress={()=>void save()} disabled={busy}/></Card></Page>;
}
