import React from 'react';
import {ActivityIndicator,Pressable,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {Order,price,quantityLabel} from './types';
export const colors={navy:'#073C60',blue:'#087FE7',bg:'#F2F7FC',muted:'#60758B',line:'#DCE7F0',green:'#098263'};
export function Page({title,kicker,children}:{title:string;kicker?:string;children:React.ReactNode}){return <SafeAreaView edges={['bottom','left','right']} style={s.safe}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={s.page}>{kicker&&<Text style={s.kicker}>{kicker}</Text>}<Text style={s.title}>{title}</Text>{children}</ScrollView></SafeAreaView>;}
export function Card({children}:{children:React.ReactNode}){return <View style={s.card}>{children}</View>;}
export function Button({label,onPress,secondary=false,disabled=false}:{label:string;onPress:()=>void;secondary?:boolean;disabled?:boolean}){return <Pressable accessibilityRole="button" accessibilityLabel={label} onPress={onPress} disabled={disabled} style={[s.button,secondary&&s.secondary,disabled&&{opacity:0.5}]}><Text style={[s.buttonText,secondary&&{color:colors.blue}]}>{label}</Text></Pressable>;}
export function Field({label,value,onChange,secure=false,numeric=false,multiline=false}:{label:string;value:string;onChange:(v:string)=>void;secure?:boolean;numeric?:boolean;multiline?:boolean}){return <View style={{marginBottom:16}}><Text style={s.label}>{label}</Text><TextInput accessibilityLabel={label} style={s.input} value={value} onChangeText={onChange} secureTextEntry={secure} multiline={multiline} keyboardType={numeric?'decimal-pad':'default'} autoCapitalize="none" /></View>;}
export function Choices({items,value,onChange}:{items:{value:string;label:string}[];value:string;onChange:(v:string)=>void}){return <View style={s.wrap}>{items.map(item=><Pressable accessibilityRole="button" accessibilityState={{selected:value===item.value}} onPress={()=>onChange(item.value)} key={item.value} style={[s.chip,value===item.value&&{backgroundColor:colors.blue,borderColor:colors.blue}]}><Text style={{fontWeight:'600',color:value===item.value?'white':colors.navy}}>{item.label}</Text></Pressable>)}</View>;}
export function Message({text,error=false}:{text:string;error?:boolean}){return text?<Text accessibilityRole={error?'alert':undefined} style={[s.message,error&&{backgroundColor:'#FFF0ED',color:'#A02B17'}]}>{text}</Text>:null;}
export function Busy(){return <ActivityIndicator style={{marginVertical:20}} color={colors.blue}/>;}
export function OrderCard({order,onPress}:{order:Order;onPress:()=>void}){return <Pressable accessibilityRole="button" accessibilityLabel={`Open order ${order.id}`} onPress={onPress} style={s.card}><Text style={s.subtitle}>{quantityLabel(order.type,order.quantity)}</Text><Text style={s.body}>{order.supplierName}</Text><Text style={s.small}>{order.address}, {order.city}</Text><View style={s.between}><Text style={s.status}>{order.status}</Text><Text style={s.amount}>{price(order.totalCents,order.currency)}</Text></View><Text style={s.small}>{order.paymentStatus==='Paid'?'Payment received':order.paymentStatus==='Unpaid'?'Payment pending':order.paymentStatus} · {order.paymentMethod==='cash'?'Cash':'EcoCash'}</Text></Pressable>;}
export const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.bg},page:{padding:22,width:'100%',maxWidth:680,alignSelf:'center',paddingBottom:40},kicker:{color:colors.muted,fontSize:10,letterSpacing:1.4,fontWeight:'800',marginBottom:10},title:{color:colors.navy,fontSize:30,lineHeight:36,fontWeight:'800',marginBottom:22,letterSpacing:-0.5},card:{padding:20,backgroundColor:'white',borderRadius:18,borderWidth:1,borderColor:colors.line,marginBottom:16},subtitle:{fontSize:18,fontWeight:'700',color:colors.navy,marginBottom:10},body:{fontSize:15,lineHeight:23,color:colors.navy},small:{fontSize:12,lineHeight:19,color:colors.muted},label:{fontSize:13,color:colors.navy,fontWeight:'700',marginBottom:8},input:{borderRadius:12,borderWidth:1,borderColor:colors.line,backgroundColor:colors.bg,padding:14,fontSize:15,color:colors.navy},button:{backgroundColor:colors.blue,borderRadius:12,padding:15,alignItems:'center',marginTop:12},secondary:{backgroundColor:'#EDF6FF',borderWidth:1,borderColor:'#CCE4FA'},buttonText:{fontSize:14,fontWeight:'700',color:'white'},wrap:{flexDirection:'row',flexWrap:'wrap',gap:8,marginBottom:18},chip:{borderRadius:10,borderWidth:1,borderColor:colors.line,backgroundColor:'white',padding:12},message:{padding:14,borderRadius:12,backgroundColor:'#E0F4EB',color:'#075C47',fontSize:13,lineHeight:20,marginBottom:16},between:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:10,marginVertical:12},amount:{fontSize:21,fontWeight:'800',color:colors.blue},status:{color:colors.green,fontSize:13,fontWeight:'700'},hero:{backgroundColor:colors.navy,padding:24,borderRadius:22,marginBottom:20},heroTitle:{fontSize:30,lineHeight:37,fontWeight:'800',color:'white',marginBottom:14},heroText:{fontSize:14,lineHeight:22,color:'#C7E1F1'}});
