import React from 'react';
import {ActivityIndicator,Pressable,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {router,usePathname} from 'expo-router';
import {Drop,Icon,IconName} from './brand';
import {useSession} from './session';
import {Order,price,quantityLabel} from './types';
export const colors={navy:'#073C60',blue:'#087FE7',bg:'#F1F8FD',muted:'#60758B',line:'#DCE7F0',green:'#098263'};
export function Page({title,kicker,children,header=true}:{title:string;kicker?:string;children:React.ReactNode;header?:boolean}){const {user}=useSession();const path=usePathname();const nav:{label:string;path:string;icon:IconName}[]=user?.role==='admin'?[{label:'Dashboard',path:'/',icon:'home'},{label:'Suppliers',path:'/admin',icon:'users'},{label:'Orders',path:'/activity',icon:'orders'},{label:'Profile',path:'/profile',icon:'user'}]:[{label:'Home',path:'/',icon:'home'},{label:'Orders',path:'/activity',icon:'orders'},{label:user?.role==='supplier'?'Earnings':'Delivery',path:user?.role==='supplier'?'/payments':'/deliveries',icon:user?.role==='supplier'?'wallet':'pin'},{label:'Profile',path:'/profile',icon:'user'}];return <SafeAreaView edges={['top','bottom','left','right']} style={s.safe}><View style={s.shell}>{header&&<View style={s.header}>{path!=='/'&&<Pressable accessibilityRole="button" accessibilityLabel="Back" onPress={()=>router.canGoBack()?router.back():router.replace('/')} style={{padding:6}}><Text style={{color:'white',fontSize:25}}>‹</Text></Pressable>}{path==='/'&&<Drop size={27}/>}<View style={{flex:1}}><Text style={{fontSize:16,color:'white',fontWeight:'700'}}>{title}</Text>{kicker&&<Text style={{fontSize:10,color:'#bfe7fb',marginTop:3}}>{kicker}</Text>}</View><Icon name={user?.role==='admin'?'shield':'water'} color="#a8e7ff" size={23}/></View>}<ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={s.page}>{children}</ScrollView>{user&&<View style={s.navigation}>{nav.map(item=><Pressable key={item.label} accessibilityRole="button" accessibilityLabel={item.label} accessibilityState={{selected:path===item.path}} onPress={()=>router.push(item.path as '/')} style={{flex:1,paddingVertical:11,alignItems:'center',gap:4}}><Icon name={item.icon} size={20} color={path===item.path?colors.blue:colors.muted}/><Text style={{fontSize:10,fontWeight:path===item.path?'800':'500',color:path===item.path?colors.blue:colors.muted}}>{item.label}</Text></Pressable>)}</View>}</View></SafeAreaView>;}
export function Card({children}:{children:React.ReactNode}){return <View style={s.card}>{children}</View>;}
export function Button({label,onPress,secondary=false,disabled=false}:{label:string;onPress:()=>void;secondary?:boolean;disabled?:boolean}){return <Pressable accessibilityRole="button" accessibilityLabel={label} onPress={onPress} disabled={disabled} style={[s.button,secondary&&s.secondary,disabled&&{opacity:0.5}]}><Text style={[s.buttonText,secondary&&{color:colors.blue}]}>{label}</Text></Pressable>;}
export function Field({label,value,onChange,secure=false,numeric=false,multiline=false}:{label:string;value:string;onChange:(v:string)=>void;secure?:boolean;numeric?:boolean;multiline?:boolean}){return <View style={{marginBottom:14}}><Text style={s.label}>{label}</Text><TextInput accessibilityLabel={label} style={s.input} value={value} onChangeText={onChange} secureTextEntry={secure} multiline={multiline} keyboardType={numeric?'decimal-pad':'default'} autoCapitalize="none" /></View>;}
export function Choices({items,value,onChange}:{items:{value:string;label:string}[];value:string;onChange:(v:string)=>void}){return <View style={s.wrap}>{items.map(item=><Pressable accessibilityRole="button" accessibilityState={{selected:value===item.value}} onPress={()=>onChange(item.value)} key={item.value} style={[s.chip,value===item.value&&{backgroundColor:colors.blue,borderColor:colors.blue}]}><Text style={{fontWeight:'600',color:value===item.value?'white':colors.navy}}>{item.label}</Text></Pressable>)}</View>;}
export function Message({text,error=false}:{text:string;error?:boolean}){return text?<Text accessibilityRole={error?'alert':undefined} style={[s.message,error&&{backgroundColor:'#FFF0ED',color:'#A02B17'}]}>{text}</Text>:null;}
export function Busy(){return <ActivityIndicator style={{marginVertical:20}} color={colors.blue}/>;}
export function OrderCard({order,onPress}:{order:Order;onPress:()=>void}){return <Pressable accessibilityRole="button" accessibilityLabel={`Open order ${order.id}`} onPress={onPress} style={s.card}><Text style={s.subtitle}>{quantityLabel(order.type,order.quantity)}</Text><Text style={s.body}>{order.supplierName}</Text><Text style={s.small}>{order.address}, {order.city}</Text><View style={s.between}><Text style={s.status}>{order.status}</Text><Text style={s.amount}>{price(order.totalCents,order.currency)}</Text></View><Text style={s.small}>{order.paymentStatus==='Paid'?'Payment received':order.paymentStatus==='Unpaid'?'Payment pending':order.paymentStatus} · {order.paymentMethod==='cash'?'Cash':'EcoCash'}</Text></Pressable>;}
export const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.bg},shell:{flex:1,width:'100%',maxWidth:480,alignSelf:'center',backgroundColor:colors.bg},header:{backgroundColor:colors.navy,paddingHorizontal:16,paddingVertical:18,flexDirection:'row',alignItems:'center',gap:10,borderBottomLeftRadius:22,borderBottomRightRadius:22},navigation:{flexDirection:'row',backgroundColor:'white',borderTopWidth:1,borderTopColor:colors.line},page:{padding:16,paddingBottom:28},kicker:{color:colors.muted,fontSize:10,letterSpacing:1.4,fontWeight:'800',marginBottom:10},title:{color:colors.navy,fontSize:32,lineHeight:38,fontWeight:'800',marginBottom:22,letterSpacing:-0.5},card:{padding:16,backgroundColor:'white',borderRadius:18,borderWidth:1,borderColor:colors.line,marginBottom:16},subtitle:{fontSize:16,fontWeight:'700',color:colors.navy,marginBottom:10},body:{fontSize:14,lineHeight:21,color:colors.navy},small:{fontSize:12,lineHeight:19,color:colors.muted},label:{fontSize:13,color:colors.navy,fontWeight:'700',marginBottom:8},input:{borderRadius:12,borderWidth:1,borderColor:colors.line,backgroundColor:colors.bg,padding:12,fontSize:14,color:colors.navy},button:{backgroundColor:colors.blue,borderRadius:12,padding:15,alignItems:'center',marginTop:12},secondary:{backgroundColor:'#EDF6FF',borderWidth:1,borderColor:'#CCE4FA'},buttonText:{fontSize:14,fontWeight:'700',color:'white'},wrap:{flexDirection:'row',flexWrap:'wrap',gap:8,marginBottom:18},chip:{borderRadius:10,borderWidth:1,borderColor:colors.line,backgroundColor:'white',padding:12},message:{padding:14,borderRadius:12,backgroundColor:'#E0F4EB',color:'#075C47',fontSize:13,lineHeight:20,marginBottom:16},between:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:10,marginVertical:12},amount:{fontSize:21,fontWeight:'800',color:colors.blue},status:{color:colors.green,fontSize:13,fontWeight:'700'},hero:{backgroundColor:colors.navy,padding:20,borderRadius:18,marginBottom:20},heroTitle:{fontSize:23,lineHeight:29,fontWeight:'800',color:'white',marginBottom:14},heroText:{fontSize:14,lineHeight:22,color:'#C7E1F1'}});

export function Steps({labels,current}:{labels:string[];current:number}){return <View accessibilityLabel={`Step ${current+1} of ${labels.length}: ${labels[current]}`} style={{flexDirection:'row',gap:8,marginBottom:24}}>{labels.map((label,index)=><View key={label} style={{flex:1}}><View style={{height:4,borderRadius:4,backgroundColor:index<=current?colors.blue:colors.line,marginBottom:8}}/><Text style={{fontSize:11,fontWeight:'700',color:index===current?colors.navy:colors.muted}}>{index+1}. {label}</Text></View>)}</View>;}
export function DeliveryProgress({status}:{status:string}){const stages=['Requested','Accepted','On the way','Arrived','Delivered'];const current=stages.indexOf(status);return <View style={{marginVertical:12}}>{current<0?<Message text={`Delivery ${status.toLowerCase()}.`}/>:stages.map((label,index)=><View key={label} style={{flexDirection:'row',alignItems:'center',gap:12,marginBottom:14}}><View style={{width:26,height:26,borderRadius:13,backgroundColor:index<=current?colors.blue:colors.line,alignItems:'center',justifyContent:'center'}}><Text style={{color:index<=current?'white':colors.muted,fontSize:12,fontWeight:'800'}}>{index<current?'✓':index+1}</Text></View><Text style={{fontSize:14,fontWeight:index===current?'800':'500',color:index<=current?colors.navy:colors.muted}}>{label==='Requested'?'Waiting for supplier':label==='Accepted'?'Supplier confirmed':label==='Delivered'?'Water received':label}</Text>{index===current&&<Text style={{fontSize:10,color:colors.blue,fontWeight:'800'}}>NOW</Text>}</View>)}</View>;}
