import {useCallback,useEffect,useRef,useState} from 'react';
import {Redirect,useLocalSearchParams} from 'expo-router';
import {Linking,Platform,Text,View} from 'react-native';
import * as Location from 'expo-location';
import {useSession} from '../../lib/session';
import DeliveryMap from '../../lib/DeliveryMap';
import {RouteEstimate} from '../../lib/map-data';
import {backgroundTrackingOrder,startBackgroundTracking,stopBackgroundTracking} from '../../lib/background-location';
import {Order,price,quantityLabel} from '../../lib/types';
import {Busy,Button,Card,Choices,DeliveryProgress,Field,Message,Page,s} from '../../lib/ui';
export default function Details(){const {id}=useLocalSearchParams<{id:string}>();const {user,api}=useSession();const [clock,setClock]=useState(()=>Date.now());const [route,setRoute]=useState<RouteEstimate|null>(null),[background,setBackground]=useState(false);const [order,setOrder]=useState<Order|null>(null),[events,setEvents]=useState<{action:string;at:string}[]>([]),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[reason,setReason]=useState(''),[phone,setPhone]=useState(''),[sharing,setSharing]=useState(false);const watcher=useRef<Location.LocationSubscription|null>(null);const orderRef=useRef<Order|null>(null);const sharingRef=useRef(false);const uploading=useRef(false);const mounted=useRef(true);
 useEffect(()=>{const timer=setInterval(()=>setClock(Date.now()),5000);return()=>clearInterval(timer);},[]);
 const load=useCallback(async()=>{if(!user)return;try{const [o,e]=await Promise.all([api<Order>(`/api/orders/${id}`),api<typeof events>(`/api/orders/${id}/events`)]);setOrder(o);orderRef.current=o;setBackground((await backgroundTrackingOrder())===id);api<RouteEstimate>(`/api/orders/${id}/route`).then(setRoute).catch(()=>setRoute({state:'unavailable',reason:'Arrival estimate unavailable.'}));setEvents(e.filter(row=>row.action!=='location'));setError('');}catch(e){setError((e as Error).message);}},[api,id,user]);
 useEffect(()=>{mounted.current=true;const initial=setTimeout(()=>void load(),0);const timer=setInterval(()=>void load(),8000);return()=>{mounted.current=false;clearTimeout(initial);clearInterval(timer);sharingRef.current=false;watcher.current?.remove();};},[load]);
 useEffect(()=>{if(order&&!['On the way','Arrived'].includes(order.status)){watcher.current?.remove();watcher.current=null;sharingRef.current=false;if(order.supplierId===user?.id)void backgroundTrackingOrder().then(active=>{if(active===id)void stopBackgroundTracking().then(()=>setBackground(false));});}},[order,user,id]);
 if(!user)return <Redirect href="/login"/>;
 const action=async(name:string,extra:Record<string,unknown>={})=>{if(!order)return;setBusy(true);setError('');try{setOrder(await api<Order>(`/api/orders/${id}/action`,{action:name,version:order.version,...extra}));await load();}catch(e){setError((e as Error).message);await load();setError((e as Error).message);}finally{setBusy(false);}};
 const share=async()=>{await stopBackgroundTracking();setBackground(false);if(sharing){sharingRef.current=false;watcher.current?.remove();watcher.current=null;setSharing(false);return;}setBusy(true);setError('');try{const permission=await Location.requestForegroundPermissionsAsync();if(!permission.granted)throw Error('Location permission denied.');sharingRef.current=true;const subscription=await Location.watchPositionAsync({accuracy:Location.Accuracy.High,timeInterval:10000,distanceInterval:20},position=>{if(!sharingRef.current||uploading.current||!['On the way','Arrived'].includes(orderRef.current?.status||''))return;uploading.current=true;api<Order>(`/api/orders/${id}/location`,{latitude:position.coords.latitude,longitude:position.coords.longitude,accuracy:position.coords.accuracy,capturedAt:position.timestamp}).then(o=>{if(mounted.current){orderRef.current=o;setOrder(o);}}).catch(e=>{if(mounted.current)setError(e.message);}).finally(()=>{uploading.current=false;});},message=>setError(message));if(!mounted.current||!sharingRef.current){subscription.remove();return;}watcher.current=subscription;setSharing(true);setNotice('Your location is shared only while this screen is open and the app is in the foreground.');}catch(e){sharingRef.current=false;setError((e as Error).message);}finally{setBusy(false);}};
 const pay=async(check=false)=>{setBusy(true);setError('');try{const response=await api<{instructions?:string;state:string}>(`/api/orders/${id}/pay/${check?'check':'ecocash'}`,check?{}:{phone});setNotice(response.instructions||`Gateway status: ${response.state}`);await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const toggleBackground=async()=>{setBusy(true);setError('');try{if(background){await stopBackgroundTracking();setBackground(false);}else{watcher.current?.remove();watcher.current=null;sharingRef.current=false;setSharing(false);await startBackgroundTracking(id);setBackground(true);setNotice('Background GPS sharing enabled for this delivery. Device battery settings and force-closing the app can interrupt tracking.');}}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const stale=!!order?.driverLocation&&clock-Date.parse(order.driverLocation.at)>120000;
 const supplier=user.id===order?.supplierId,customer=user.id===order?.customerId;
 const openMap=(lat:number,lon:number)=>void Linking.openURL(`https://www.google.com/maps/search/?api=1&query=${lat},${lon}`).catch(e=>setError(e.message));
 return <Page title="Delivery details" kicker={order?.id}><Message text={error} error/><Message text={notice}/>{!order?<Busy/>:<><Card><Text style={s.status}>{order.status}</Text><Text style={[s.subtitle,{marginTop:12}]}>{quantityLabel(order.type,order.quantity)}</Text><Text style={s.body}>{order.supplierName}</Text><Text style={s.small}>{order.address}, {order.city}</Text><Text style={[s.amount,{marginTop:18}]}>{price(order.totalCents,order.currency)}</Text><Text style={s.small}>{order.paymentMethod==='cash'?'Cash on delivery':'EcoCash'} · {order.paymentStatus}</Text><Button label={supplier?'Call customer':'Call supplier'} secondary onPress={()=>void Linking.openURL(`tel:${supplier?order.customerPhone:order.supplierPhone}`).catch(e=>setError(e.message))}/>{order.location&&<Button label="Open delivery location" secondary onPress={()=>openMap(order.location!.latitude,order.location!.longitude)}/>}</Card><Card><Text style={s.subtitle}>Your delivery progress</Text><DeliveryProgress status={order.status}/><Text style={[s.small,{marginBottom:14}]}>The map shows reported phone GPS, not a guaranteed exact location.</Text>{(order.location||order.driverLocation)&&<DeliveryMap destination={order.location} driver={order.driverLocation} stale={stale} route={!stale&&route?.state==='available'?route.coordinates:undefined}/>}<Message text={stale?'Tracking paused · last GPS update is over two minutes old.':''} error/>{!stale&&route?.state==='available'&&order.status==='On the way'?<><Text style={[s.amount,{marginTop:14}]}>About {Math.max(1,Math.ceil((route.durationSeconds||0)/60))} min away</Text><Text style={s.small}>{((route.distanceMeters||0)/1000).toFixed(1)} km by road · no live traffic · estimate updated {route.computedAt?new Date(route.computedAt).toLocaleTimeString():''}</Text></>:<Text style={s.small}>{route?.reason||'Waiting for an arrival estimate.'}</Text>}{order.driverLocation?<><Text style={s.body}>Last GPS update: {new Date(order.driverLocation.at).toLocaleTimeString()}</Text><Text style={s.small}>GPS accuracy: {order.driverLocation.accuracy===null?'unavailable':`about ${Math.round(order.driverLocation.accuracy)} m`}. A grey marker means the location is stale.</Text><Button label="View supplier on map" secondary onPress={()=>openMap(order.driverLocation!.latitude,order.driverLocation!.longitude)}/></>:<Text style={s.body}>No driver location received yet.</Text>}{supplier&&['On the way','Arrived'].includes(order.status)&&<><Button label={sharing?'Stop screen-only tracking':'Share GPS while this screen is open'} onPress={()=>void share()} disabled={busy}/>{Platform.OS!=='web'&&<><Text style={[s.small,{marginTop:12}]}>Background sharing sends your GPS to this delivery’s customer and operator while the app is minimised. Enable only during delivery.</Text><Button label={background?'Stop background tracking':'Enable background delivery tracking'} secondary onPress={()=>void toggleBackground()} disabled={busy}/></>}</>}</Card>
 {supplier&&['Requested','Accepted','On the way'].includes(order.status)&&<Button label={order.status==='Requested'?'Accept order':order.status==='Accepted'?'Start delivery':'Mark arrival'} disabled={busy} onPress={()=>void action(order.status==='Requested'?'accept':order.status==='Accepted'?'depart':'arrive')}/>}
 {customer&&order.status==='Arrived'&&<Button label="Confirm water received" disabled={busy} onPress={()=>void action('receive')}/>}
 {['Requested','Accepted'].includes(order.status)&&(supplier||customer)&&<Card><Field label={customer?'Cancellation reason':'Decline reason'} value={reason} onChange={setReason}/><Button label={customer?'Cancel order':'Decline order'} secondary disabled={busy} onPress={()=>void action(customer?'cancel':'decline',{reason})}/></Card>}
 {order.status==='Delivered'&&<Card><Text style={s.subtitle}>Payment & receipt</Text><Text style={s.body}>{order.paymentStatus==='Paid'?'Payment received':order.paymentStatus==='Unpaid'?'Payment pending':order.paymentStatus} · {price(order.totalCents,order.currency)}</Text>{supplier&&order.paymentMethod==='cash'&&order.paymentStatus!=='Paid'&&<Button label="Confirm cash collected" disabled={busy} onPress={()=>void action('cash')}/>} {customer&&order.paymentMethod==='ecocash'&&order.paymentStatus==='Unpaid'&&<><Field label="EcoCash phone" value={phone} onChange={setPhone}/><Button label="Request EcoCash payment" disabled={busy} onPress={()=>void pay()}/><Button label="Check payment status" secondary disabled={busy} onPress={()=>void pay(true)}/></>}{customer&&<><Text style={[s.label,{marginTop:20}]}>Delivery rating {order.rating?`· ${order.rating}/5`:''}</Text><Choices items={[1,2,3,4,5].map(n=>({value:`${n}`,label:`${n} ★`}))} value={`${order.rating||''}`} onChange={v=>void action('rate',{rating:Number(v)})}/></>}</Card>}
 {user.role==='admin'&&order.paymentMethod==='ecocash'&&<Button label="Reconcile EcoCash payment" secondary disabled={busy} onPress={()=>void pay(true)}/>}{!!order.reason&&<Card><Text style={s.subtitle}>Reason</Text><Text style={s.body}>{order.reason}</Text></Card>}
 <Card><Text style={s.subtitle}>Order history</Text>{events.map((event,index)=><View key={index} style={{marginBottom:12}}><Text style={s.body}>{event.action}</Text><Text style={s.small}>{new Date(event.at).toLocaleString()}</Text></View>)}</Card><Button label="Refresh delivery" secondary onPress={()=>void load()}/></>}</Page>;
}
